a = float(input("Bill subtotal: "))
b = float(input("Tip percent: "))
c = int(input("Number of people: "))
t = round(a*b/100,2)
g = round(a+t,2)
p = round(g/c,2)
print(f"Tip ({b:.0f}%): ${t:.2f}")
print(f"Grand total: ${g:.2f}")
print(f"Per person ({c}): ${p:.2f}")
if b>=20:
    print("That's a generous tip! 🎉")
